name: build keywriter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: curl xz-utils python git golang-go wget qtcreator
          version: 1.0

      - name: pull submodules
        run: |
          git submodule init
          git submodule update --remote

      - name: Get toolchain
        run: curl https://storage.googleapis.com/remarkable-codex-toolchain/remarkable-platform-image-4.0.117-rm1-public-x86_64-toolchain.sh -o install-toolchain.sh

      - name: make toolchain executable
        run: chmod +x ./install-toolchain.sh

      - name: Install toolchain
        run: |
            locale
            ./install-toolchain.sh

      - name: Build
        run: |
          source /opt/codex/rm1/4.0.117/environment-setup-cortexa9hf-neon-remarkable-linux-gnueabi
          qmake edit.pro -spec linux-oe-g++ -qt=qt6
          /usr/bin/make

      - name: where are all the files?
        run: find .

      - uses: actions/upload-artifact@v2
        with:
          name: keywriter
          path: edit
