name: build keywriter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: update apt-cache
        run: apt-get update

      - name: Install apt packages needed for build
        run: apt-get install -y curl xz-utils python git golang-go bsdtar wget

      - name: pull submodules
        run: |
          git submodule init
          git submodule update --remote

      - name: Get toolchain
        run: curl https://storage.googleapis.com/remarkable-codex-toolchain/remarkable-platform-image-4.0.117-rm1-public-x86_64-toolchain.sh -o install-toolchain.sh

      - name: make toolchain executable
        run: chmod +x ./install-toolchain.sh

      - name: Install toolchain
        run: |
            locale
            ./install-toolchain.sh

      - name: Install qtcreator
        run: apt-get install -y qtcreator

      - name: Install ghr before sourcing new toolchain
        run: |
            wget https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz
            tar -xvf go1.14.2.linux-amd64.tar.gz
            mv go /usr/local/
            export GOROOT=/usr/local/go
            mkdir -p ./go
            export GOPATH=`pwd`/go
            export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
            go get -u github.com/tcnksm/ghr

      - name: Build
        run: |
          ls /usr/local
          source /usr/local/oecore-x86_64/environment-setup-cortexa9hf-neon-oe-linux-gnueabi
          qmake edit.pro -spec linux-oe-g++
          /usr/bin/make

      - name: where are all the files?
        run: find .

      - uses: actions/upload-artifact@v2
        with: 
          path: edit
